src/EMM/UserBundle/Entity/User.php
<?php

namespace EMM\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * User
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="EMM\UserBundle\Entity\UserRepository")
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements AdvancedUserInterface, \Serializable
{
    
    /**
     * @ORM\OneToMany(targetEntity="Task", mappedBy="user")
     */ 
    protected $tasks;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=50)
     * @Assert\NotBlank()
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=100)
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="role", type="string", columnDefinition="ENUM('ROLE_ADMIN', 'ROLE_USER')", length=50)
     * @Assert\NotBlank()
     * @Assert\Choice(choices = {"ROLE_ADMIN", "ROLE_USER"})
     */
    private $role;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->isActive = true;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string 
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set role
     *
     * @param string $role
     * @return User
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get role
     *
     * @return string 
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return User
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return User
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }
    
    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }
    
    public function getRoles()
    {
        return array($this->role);
    }
    
    public function getSalt()
    {
        return null;
    }
    
    public function eraseCredentials()
    {
        
    }

    /**
     * Add tasks
     *
     * @param \EMM\UserBundle\Entity\Task $tasks
     * @return User
     */
    public function addTask(\EMM\UserBundle\Entity\Task $tasks)
    {
        $this->tasks[] = $tasks;

        return $this;
    }

    /**
     * Remove tasks
     *
     * @param \EMM\UserBundle\Entity\Task $tasks
     */
    public function removeTask(\EMM\UserBundle\Entity\Task $tasks)
    {
        $this->tasks->removeElement($tasks);
    }

    /**
     * Get tasks
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTasks()
    {
        return $this->tasks;
    }
    
    public function getFullName()
    {
        return $this->firstName . " " . $this->lastName;
    }
    
    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActive
        ) = unserialize($serialized);
    }   
    
    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }
}

src/EMM/UserBundle/Form/TaskType.php
<?php

namespace EMM\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Doctrine\ORM\EntityRepository;

class TaskType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('user', 'entity', array(
                'class' => 'EMMUserBundle:User',
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where('u.role = :only')
                        ->setParameter('only', 'ROLE_USER');
                },
                'choice_label' => 'getFullName'
            ))
            ->add('save', 'submit', array('label' => 'Save task'))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'EMM\UserBundle\Entity\Task'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'task';
    }
}

src/EMM/UserBundle/Controller/TaskController.php
<?php

namespace EMM\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response; 
use EMM\UserBundle\Entity\Task;
use EMM\UserBundle\Form\TaskType;

class TaskController extends Controller
{
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $dql = "SELECT t FROM EMMUserBundle:Task t ORDER BY t.id DESC";
        $tasks = $em->createQuery($dql);
        
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $tasks,
            $request->query->getInt('page', 1),
            3
        );
        
        return $this->render('EMMUserBundle:Task:index.html.twig', array('pagination' => $pagination));
    }
    
    public function customAction(Request $request)
    {
        $idUser = $this->get('security.token_storage')->getToken()->getUser()->getId();
        
        $em = $this->getDoctrine()->getManager();
        $dql = "SELECT t FROM EMMUserBundle:Task t JOIN t.user u WHERE u.id = :idUser ORDER BY t.id DESC";
        
        $tasks = $em->createQuery($dql)->setParameter('idUser' , $idUser);
        
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $tasks,
            $request->query->getInt('page', 1),
            3
        );
        
        $updateForm = $this->createCustomForm(':TASK_ID', 'PUT', 'emm_task_process');
        
        return $this->render('EMMUserBundle:Task:custom.html.twig', array('pagination' => $pagination, 'update_form' => $updateForm->createView()));
    }
    
    public function processAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        
        $task = $em->getRepository('EMMUserBundle:Task')->find($id);
        
        if(!$task)
        {
            throw $this>createNotFoundException('Task not found');
        }
        
        $form = $this->createCustomForm($task->getId(), 'PUT', 'emm_task_process');
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid())
        {
            
            $successMessage = $this->get('translator')->trans('The task has been processed.');
            $warningMessage = $this->get('translator')->trans('The task has already been processed.');
            
            if ($task->getStatus() == 0)
            {
                $task->setStatus(1);
                $em->flush();
                
                if($request->isXMLHttpRequest())
                {
                    return new Response(
                        json_encode(array('processed' => 1, 'success' => $successMessage)),
                        200,
                        array('Content-Type' => 'application/json')
                    );
                }
            }
            else
            {
                if($request->isXMLHttpRequest())
                {
                    return new Response(
                        json_encode(array('processed' => 0, 'warning' => $warningMessage)),
                        200,
                        array('Content-Type' => 'application/json')
                    );
                }            
            }
        }
    }
    
    public function addAction()
    {
        $task = new Task();
        $form = $this->createCreateForm($task);
        
        return $this->render('EMMUserBundle:Task:add.html.twig', array('form' => $form->createView()));
    }
    
    private function createCreateForm(Task $entity)
    {
        $form = $this->createForm(new TaskType(), $entity, array(
            'action' => $this->generateUrl('emm_task_create'),
            'method' => 'POST'
        ));
        
        return $form;
    }
    
    public function createAction(Request $request)
    {
        $task = new Task();
        $form = $this->createCreateForm($task);
        $form->handleRequest($request);
        
        if($form->isValid())
        {
            $task->setStatus(0);
            $em = $this->getDoctrine()->getManager();
            $em->persist($task);
            $em->flush();
            
            $successMessage = $this->get('translator')->trans('The task has been created.');
            $this->addFlash('mensaje', $successMessage);            
            
            return $this->redirectToRoute('emm_task_index');
        }
        
        return $this->render('EMMUserBundle:Task:add.html.twig', array('form' => $form->createView()));
    }
    
    public function viewAction($id)
    {
        $task = $this->getDoctrine()->getRepository('EMMUserBundle:Task')->find($id);
        
        if(!$task)
        {
            throw $this->createNotFoundException('The task does not exist.');
        }
        
        $deleteForm = $this->createCustomForm($task->getId(), 'DELETE', 'emm_task_delete');
        
        $user = $task->getUser();
        
        return $this->render('EMMUserBundle:Task:view.html.twig', array('task' => $task, 'user' => $user, 'delete_form' => $deleteForm->createView()));
    }
    
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $task = $em->getRepository('EMMUserBundle:Task')->find($id);
        
        if(!$task)
        {
            throw $this->createNotFoundException('task not found');
        }
        
        $form = $this->createEditForm($task);
        
        return $this->render('EMMUserBundle:Task:edit.html.twig', array('task' => $task, 'form' => $form->createView()));
    }
    
    private function createEditForm(Task $entity)
    {
        $form = $this->createForm(new TaskType(), $entity, array(
            'action' => $this->generateUrl('emm_task_update', array('id' => $entity->getId())),
            'method' => 'PUT'
        ));
        
        return $form;
    }
    
    public function updateAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        
        $task = $em->getRepository('EMMUserBundle:Task')->find($id);
        
        if(!$task)
        {
            throw $this->createNotFoundException('task not found');
        }
        
        $form = $this->createEditForm($task);
        $form->handleRequest($request);
        
        if($form->isSubmitted() and $form->isValid())
        {
            $task->setStatus(0);
            $em->flush();
            $successMessage = $this->get('translator')->trans('The task has been modified.');
            $this->addFlash('mensaje', $successMessage);            
            return $this->redirectToRoute('emm_task_edit', array('id' => $task->getId()));
        }
        
        return $this->render('EMMUserBundle:Task:edit.html.twig', array('task' => $task, 'form' => $form->createView()));
    }
    
    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $task = $em->getRepository('EMMUserBundle:Task')->find($id);
        
        if(!$task)
        {
            throw $this->createNotFoundException('task not found');
        }
        
        $form = $this->createCustomForm($task->getId(), 'DELETE', 'emm_task_delete');
        $form->handleRequest($request);
        
        if($form->isSubmitted() and $form->isValid())
        {
            $em->remove($task);
            $em->flush();
            
            $successMessage = $this->get('translator')->trans('The task has been deleted.');
            $this->addFlash('mensaje', $successMessage); 
            
            return $this->redirectToRoute('emm_task_index');
        }
    }
    
    private function createCustomForm($id, $method, $route)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl($route, array('id' => $id)))
            ->setMethod($method)
            ->getForm();
    }
}

src/EMM/UserBundle/Resources/views/Task/add.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    {{ parent() }}
	<div class="main container">
		<div class="row well">
			<div class="col-md-6">
				<div class="page-header">
					<h2>{% trans %}New task{% endtrans %}</h2>
				</div>
				{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role' : 'form'}}) }}
				    <h4 class="text-danger">{{ form_errors(form) }}</h4>

					<fieldset>
					    <div class="form-group">
					        {{ form_label(form.title) }}
					        {{ form_widget(form.title, {'attr': {'class': 'form-control', 'placeholder' : 'Task title'}}) }}
					        <span class="text-danger">{{ form_errors(form.title) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.user) }}
					        {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
					        <span class="text-danger">{{ form_errors(form.user) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.description) }}
					        {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder' : 'Task description'}}) }}
					        <span class="text-danger">{{ form_errors(form.description) }}</span>
					    </div>
					</fieldset>

				    <p>
				        {{ form_widget(form.save, {'label' : 'Create task', 'attr': {'class': 'btn btn-success'}}) }}
				    </p>

				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}

src/EMM/UserBundle/Resources/views/Task/custom.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
	{{ parent() }}

	{{ include('EMMUserBundle:Task:messages/success.html.twig') }}
	{{ include('EMMUserBundle:Task:messages/warning.html.twig') }}

	<div class="container">
		<div class="col-md-12">
			<div class="page-header margin-none">
				<h2 class="padding-none">{{ 'Tasks'|trans }}</h2>
			</div>
			{% if not pagination|length %}
				<h3>{{ 'No tasks'|trans }}</h3>
			{% endif %}
			{% if pagination|length %}
			<div class="table-responsive">
				<p>
				    {{ 'Total records:'|trans }} <span id="total"> {{ pagination.getTotalItemCount }} </span>
				</p>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>{{ knp_pagination_sortable(pagination, 'Title'|trans, 't.title') }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Date'|trans, 't.createdAt') }}</th>
							<th>{{ 'User'|trans }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Status'|trans, 't.status') }}</th>
							<th>{{ 'Actions'|trans }}</th>
						</tr>
					</thead>
					<tbody>
				        {% for task in pagination %}
				            <tr data-id="{{ task.id }}">
				                <td>
				                	<a href="{{ path('emm_task_view', { id: task.id }) }}">{{ task.title }}</a>
				                </td>
				                <td>{{ task.createdAt|date('d-m-Y H:i') }}</td>
				                <td>{{ task.user.firstName }} {{ task.user.lastName }}</td>
				                <td>
				                	{% if task.status == 0 %}
										<span class="glyphicon glyphicon-time text-danger" title="Waiting" id="glyphicon-{{task.id}}"></span>
									{% elseif task.status == 1 %}
										<span class="glyphicon glyphicon-ok text-success" title="Finish"></span>
				                	{% endif %}
								</td>
								<td class="actions">
								    <a href="#" class="btn btn-sm btn-success btn-process" id="button-{{ task.id }}">
								        {{ 'Finalize'|trans }}
								    </a>
								</td>
				            </tr>
				        {% endfor %}
					</tbody>
				</table>
			{# display navigation #}
			<div class="navigation">
			    {{ knp_pagination_render(pagination) }}
			</div>
			</div>
			{% endif %}
		</div>
	</div>
	
	{{ include('EMMUserBundle:User:forms/form.html.twig', {form: update_form, id: 'form-update', with_submit: false, message: null}) }}
	
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/emmuser/js/task-process.js') }}"></script>
{% endblock %}

src/EMM/UserBundle/Resources/views/Task/edit.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    {{ parent() }}
    {{ include('EMMUserBundle:Task:messages/success.html.twig') }}
	<div class="main container">
		<div class="row well">
			<div class="col-md-6">
				<div class="page-header">
					<h2>{{ 'Edit task'|trans }}</h2>
				</div>
				{{ form_start(form, {'attr': {'novalidate': 'novalidate', 'role' : 'form'}}) }}
				    <h4 class="text-danger">{{ form_errors(form) }}</h4>

					<fieldset>
					    <div class="form-group">
					        {{ form_label(form.title) }}
					        {{ form_widget(form.title, {'attr': {'class': 'form-control', 'placeholder' : 'Task title'}}) }}
					        <span class="text-danger">{{ form_errors(form.title) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.user) }}
					        {{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
					        <span class="text-danger">{{ form_errors(form.user) }}</span>
					    </div>

					    <div class="form-group">
					        {{ form_label(form.description) }}
					        {{ form_widget(form.description, {'attr': {'class': 'form-control', 'placeholder' : 'Task description'}}) }}
					        <span class="text-danger">{{ form_errors(form.description) }}</span>
					    </div>
					</fieldset>

				    <p>
				        {{ form_widget(form.save, {'label' : 'Update task'|trans, 'attr': {'class': 'btn btn-success'}}) }}
				    </p>

				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}

src/EMM/UserBundle/Resources/views/Task/index.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
	{{ parent() }}
	
    {{ include('EMMUserBundle:Task:messages/success.html.twig') }}
    
	<div class="container">
		<div class="col-md-12">
			<div class="page-header margin-none">
				<h2 class="padding-none">{% trans %}Tasks{% endtrans %}</h2>
			</div>
			<div class="table-responsive">
				<p>
				    {% trans %}Total records: {% endtrans %} <span id="total"> {{ pagination.getTotalItemCount }} </span>
				</p>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>{{ knp_pagination_sortable(pagination, 'Title'|trans, 't.title') }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Date'|trans, 't.createdAt') }}</th>
							<th>{{ 'User'|trans }}</th>
							<th>{{ knp_pagination_sortable(pagination, 'Status'|trans, 't.status') }}</th>
						</tr>
					</thead>
					<tbody>
				        {% for task in pagination %}
				            <tr data-id="{{ task.id }}">
				                <td>
				                	<a href="{{ path('emm_task_view', {id: task.id}) }}">{{ task.title }}</a>
				                </td>
				                <td>{{ task.createdAt|date('d-m-Y H:i') }}</td>
				                <td>{{ task.user.fullName }}</td>
				                <td>
				                	{% if task.status == 0 %}
										<span class="glyphicon glyphicon-time text-danger" title="{% trans %}Waiting{% endtrans %}" id="glyphicon-{{task.id}}"></span>
									{% elseif task.status == 1 %}
										<span class="glyphicon glyphicon-ok text-success" title="{% trans %}Finish{% endtrans %}"></span>
				                	{% endif %}
								</td>
				            </tr>
				        {% endfor %}
					</tbody>
				</table>
			{# display navigation #}
			<div class="navigation">
			    {{ knp_pagination_render(pagination) }}
			</div>
			</div>
		</div>
	</div>
{% endblock %}

src/EMM/UserBundle/Resources/views/Task/view.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
	{{ parent() }}
	<div class="container well">
	    <div class="col-md-9">
	    <h2>{{ task.title }}</h2>
	        <br>
	        <dl>
	            <dt>{{ 'Description'|trans }}</dt>
	            <dd>
	                {{ task.description }}
	                &nbsp;
	            </dd>
	            <br>

	            <dt>{{ 'User'|trans }}</dt>
	            <dd>
	                {{ user.fullName }}
	                &nbsp;
	            </dd>
	            <br>

	            <dt>{{ 'Status'|trans }}</dt>
	            <dd>
                	{% if task.status == 0 %}
                	    <span class="text-danger">{{ 'Waiting'|trans }}</span>
                	{% elseif task.status == 1 %}
                	    <span class="text-success">{{ 'Finish'|trans }}</span>
                	{% endif %}
	                &nbsp;
	            </dd>
	            <br>

	            <dt>{{ 'Created'|trans }}</dt>
	            <dd>
	                {{ task.createdAt|date('d-m-Y H:i') }}
	                &nbsp;
	            </dd>
	            <br>

	            <dt>{{ 'Updated'|trans }}</dt>
	            <dd>
	                {{ task.updatedAt|date('d-m-Y H:i') }}
	                &nbsp;
	            </dd>
	            <br>
	        </dl>
	    </div>
	    {% if is_granted('ROLE_ADMIN') %}
	    <div class="col-md-3">
	        <h3>{{ 'Actions'|trans }}:</h3>
	        <p>
	            <a href="{{ path('emm_task_edit', {id: task.id}) }}" class="btn btn-primary btn-lg btn-block">
	                <span class="glyphicon glyphicon-edit"></span>
	                {{ 'Edit task'|trans }}
	            </a>
	        </p>
	        <p>
	            {{ include('EMMUserBundle:Task:forms/form.html.twig', { form: delete_form, message: 'Are you sure ?'|trans }) }}
	        </p>
	    </div>
	    {% endif %}
	</div>
{% endblock %}